app:
  name: SimpleLoginRegister
  version: 1.0.0
  port: :8080

database:
  dsn: root:123456@tcp(127.0.0.1:3306)/user?charset=utf8mb4&parseTime=True&loc=Local
  MaxIdleConns: 10
  MaxOpenConns: 100

cors:
  AllowOrigins:
    - "http://localhost:5173"
    - "http://127.0.0.1:5173"

